---
- name: Set cluster variables
  set_fact:
    cluster_name: "{{ cluster_config.cluster_name }}"
    install_dir: "{{ cluster_config.install_dir }}"
    tmux_session: "{{ cluster_config.tmux_session }}"

- name: Include install-config creation tasks
  include_tasks: install_config.yml

- name: Include tmux check tasks
  include_tasks: tmux_check.yml
