---
- name: Create AWS credentials Secret for cert-manager
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: route53-credentials
        namespace: cert-manager
      type: Opaque
      stringData:
        access-key-id: "{{ certmanager_aws_access_key_id }}"
        secret-access-key: "{{ certmanager_aws_secret_access_key }}"
  no_log: true
